#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default BAT1_N_CELLS 4
param set-default BAT1_CAPACITY 6800
param set-default BAT1_V_EMPTY 3.6
param set-default BAT1_V_CHARGED 4.2

# NOTE: the index order does not match the gazebo model!
# CA params use the FRD coordinates (X+ is in front of the center of mass (CoM), Y+ is right of CoM, Z+ is below CoM)

param set-default CA_ROTOR0_PX 0.1812
param set-default CA_ROTOR0_PY 0.1812
param set-default CA_ROTOR0_PZ -0.057
param set-default CA_ROTOR0_CT 1.0
param set-default CA_ROTOR0_KM 0.06

param set-default CA_ROTOR1_PX -0.1812
param set-default CA_ROTOR1_PY -0.1812
param set-default CA_ROTOR1_PZ -0.057
param set-default CA_ROTOR1_CT 1.0
param set-default CA_ROTOR1_KM 0.06

param set-default CA_ROTOR2_PX 0.1812
param set-default CA_ROTOR2_PY -0.1812
param set-default CA_ROTOR2_PZ -0.057
param set-default CA_ROTOR2_CT 1.0
param set-default CA_ROTOR2_KM -0.06

param set-default CA_ROTOR3_PX -0.1812
param set-default CA_ROTOR3_PY 0.1812
param set-default CA_ROTOR3_PZ -0.057
param set-default CA_ROTOR3_CT 1.0
param set-default CA_ROTOR3_KM -0.06

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.47

# param set-default MC_ROLLRATE_P 0.09
# param set-default MC_PITCHRATE_P 0.09
# param set-default MC_ROLLRATE_I 0.04
# param set-default MC_PITCHRATE_I 0.04
# param set-default MC_ROLLRATE_D 0.0025
# param set-default MC_PITCHRATE_D 0.0025
# param set-default MC_ROLLRATE_FF 0.0
# param set-default MC_PITCHRATE_FF 0.0
