#!/bin/sh
#
# @name DJI F450 SITL
#
# @type Quadcopter x
#
# @maintainer Petr Stibinger <stibipet@fel.cvut.cz>
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}

param set-default SIM_GZ_EN 1
