uav_mass: 4.84

motor_params:
  n_motors: 4
  a: 0.167524
  b: 0.000413

mrs_uav_managers:

  constraint_manager:

    default_constraints:
      gps_garmin: "medium"
      gps_baro: "medium"
      rtk: "medium"
      aloam: "slow"
      hector_garmin: "slow"
      vio: "slow"
      optflow: "slow"
      other: "slow"
      ground_truth: "medium"
